### PR TITLE
Add support for nested main field selectors

### LINKED ISSUE #217: Correct mainFields type
The type of `mainFields` is set to `string[]` in a few places, including the signature of `createMatchPathAsync`.

The correct type is `(string | string[])[]`:

https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/types.d.ts#L9767

This test case confirms the type is correct:

https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/test/TestCases.template.js#L149-L156

For type safety, it would be great if this package were compatible with the Webpack type of `mainFields`, foregoing the need for type assertions. Thanks!

### PR DESCRIPTION
**Pull request by aaronadamsCA**
Fixes #217.

There's some slightly repetitive code, I just wasn't sure where a common function should live, so I left the minor copy-paste.

### CODE REVIEW

**Comment by jonaskello** [comment]
Altough I would prefer to keep webpack specific stuff in the webpack plugin, resolving nested fields cannot be done in the plugin so I guess we need to add this.

**Comment by jonaskello** [comment]
The jsdoc currently says this about the mainFields param:

```
@param mainFields A list of package.json field names to try when resolving module files.
```

@aaronadamsCA Could you update that comment to reflect the new function? Also the same comment is in the readme.

**Comment by aaronadamsCA** [comment]
> Altough I would prefer to keep webpack specific stuff in the webpack plugin, resolving nested mainfields in package.json cannot be done in the plugin so I guess we need to add this.

If you prefer, I can update the downstream PR instead to just throw an error if the script reaches an array. This syntax does not appear to be in wide use anymore; it relates to a proposal that never went anywhere.

> The jsdoc currently says this about the mainFields param:
> 
> ```
> @param mainFields A list of package.json field names to try when resolving module files.
> ```
> 
> @aaronadamsCA Could you update that comment to reflect the new function? Also the same comment is in the readme.

Done.

**Comment by jonaskello** [comment]
I think we could have this for completeness so let's merge it and then look into the downstream PR.

**Comment by jonaskello** [comment]
Released in 4.1.0

**Pull request merged**
