### PR TITLE
Fix the root path

### LINKED ISSUE #128: Does not work for path mapping starting with `/`
I have tsconfig paths configured as:
```json
"paths": {
      "/@utils/*": ["src/utils/*"],
      "/@services/*": ["src/services/*"],
      "/@contexts/*": ["src/contexts/*"],
      "/@translations/": ["src/services/system/localization/translations/index"]
},
```

These fail to resolve to the correct paths due to this line in code: 
https://github.com/dividab/tsconfig-paths/blob/master/src/try-path.ts#L27

Do we need this check ?

### PR DESCRIPTION
**Pull request by benevbright**
fixes #128

### CODE REVIEW

**Comment by rattrayalex** [comment]
Also fixes https://github.com/dividab/tsconfig-paths/issues/113

**Comment by jonaskello** [comment]
There seems to be a demand for this in both #113 and #128 so it would of course be nice to have it merged.

@benevbright could you also add some tests for both the positive and negative cases of this?

**Comment by benevbright** [comment]
@jonaskello I've added a test. Thanks! 👍

**Comment by jonaskello** [comment]
Released in 3.14.0

**Pull request merged**
