### PR TITLE
Fix problem with tslint-loader (issue #15)

### PR DESCRIPTION
**Pull request by stenin-nikita**

### CODE REVIEW

**Comment by jonaskello** [comment]
@stenin-nikita Could you provide some reasoning behind this PR? Seems like it removes the handling of core modules in favour of a try/catch. Could you explain why this would solve the problem in #15?

**Comment by jonaskello** [comment]
Ok, I think I understand the problem, I made a comment in the issue as it seems better to discuss the root cause there.

I would prefer a solution that does not involve try/catch for each resolve. In part because my view is that exceptions are for unexpected errors, but mostly because I think it will affect performance. I think maybe we can understand what is causing this and then check it before resolving instead. However to do this I would need to recreate the issue in #15.

**Comment by aleclarson** [comment]
@jonaskello  This can probably be closed, since tslint is now deprecated?

**Comment by jonaskello** [comment]
Yes, let's close this one. I think most projects are using eslint now.

**Pull request closed without merging**
