### PR TITLE
Add support for extends as array of strings to v3 (backport of #245)

### PR DESCRIPTION
**Pull request by domdomegg**
TypeScript 5.0 added support for defining "extends" as an array of strings. This commit adds support for this use case.

This is a backport of #245, which fixes:
- https://github.com/dividab/tsconfig-paths/issues/259
- https://github.com/import-js/eslint-plugin-import/pull/2447#issuecomment-1653491616
- https://github.com/import-js/eslint-plugin-import/issues/2890

This should be releasable as a minor version, e.g. 3.15.0

### CODE REVIEW

**Comment by ljharb** [comment]
Landing and releasing this would be amazing, and would enable the feature for 81% of this package's users https://majors.nullvoxpopuli.com/q?old=on&packages=tsconfig-paths

**Comment by ljharb** [comment]
cc @jonaskello

**Comment by nonameolsson** [comment]
Looking forward to this! 
Here is why https://github.com/import-js/eslint-plugin-import/issues/2938#issuecomment-1852351268

**Comment by jonaskello** [comment]
Since #245 seems to be working I think we can merge this.

**Comment by jonaskello** [comment]
Released in 3.15.0

**Pull request merged**
