### PR TITLE
Update json5 to 2.2.x

### PR DESCRIPTION
**Pull request by stianjensen**
The new version bundles typescript types.

### CODE REVIEW

**Comment by airarrazaval** [comment]
`json5@2.2.0` has a vulnerability inherited by one of its dependencies (`minimist`).

https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795

This must be updated to `json5@2.2.1` which removes `minimist` as dependency.

**Comment by stianjensen** [comment]
Updated

**Comment by stianjensen** [comment]
Ah! Node 4 has been unsupported for 4 years, so I didn't realize that was still breaking. I guess whenever you're shipping a new major version, then.

**Comment by jonaskello** [comment]
Let's merge this now when we are doing a new major.

**Comment by F3n67u** [comment]
This breaking change will potentially block https://github.com/import-js/eslint-plugin-import and https://github.com/alexgorbatchev/eslint-import-resolver-typescript to upgrade to 4..0.0 as far as I know. Those package's minimum nodejs version is v4.

**Comment by stianjensen** [comment]
> This breaking change will potentially block https://github.com/import-js/eslint-plugin-import and https://github.com/alexgorbatchev/eslint-import-resolver-typescript to upgrade to 4..0.0 as far as I know. Those package's minimum nodejs version is v4.

Node 4 has been unsupported for 4(!) years now, so I really hope no one is still using that in production and are also depending on new versions of those packages still supporting it.

eslint itself doesn't support anything below 12 as of version 8, and anyone on old eslint version can also continue using old versions of eslint-plugin-import if they have to.

**Comment by F3n67u** [comment]
> > This breaking change will potentially block https://github.com/import-js/eslint-plugin-import and https://github.com/alexgorbatchev/eslint-import-resolver-typescript to upgrade to 4..0.0 as far as I know. Those package's minimum nodejs version is v4.
> 
> Node 4 has been unsupported for 4(!) years now, so I really hope no one is still using that in production and are also depending on new versions of those packages still supporting it.
> 
> eslint itself doesn't support anything below 12 as of version 8, and anyone on old eslint version can also continue using old versions of eslint-plugin-import if they have to.

I agree with you. but I am not sure if there are any special cases where node v4 is a must to have. I make draft pr to bump `tsconfig-paths` version to `v4` on https://github.com/import-js/eslint-plugin-import/pull/2447 and https://github.com/alexgorbatchev/eslint-import-resolver-typescript/pull/104 to collect some feedback.

**Comment by ljharb** [comment]
@stianjensen being unsupported is irrelevant; eslint-plugin-import supports down to eslint 2 (and associated node version) and will continue to do so.

**Pull request merged**
