### PR TITLE
For review of #135

### PR DESCRIPTION
**Pull request by cspotcode**
This PR is meant to be #135, but I had to push to a different branch.

### CODE REVIEW

**Comment by jonaskello** [comment]
Thanks for picking this up :-) LGTM

**Comment by jonaskello** [comment]
@cspotcode I can add you to npm too so you can publish if you want?

**Comment by cspotcode** [comment]
That'd be great, thanks.

Should this be a patch release or a major release?  Anything I need to know
about the release process, extra steps, changelog tooling, stuff like that?

**Comment by jonaskello** [comment]
The changelog is manually updated. Just move the unreleased heading to new version heading before publishing (and remember to make a compare link like for the other version headings, and update the unreleased link too). I usually do this directly on master. If you have ideas for automating this more I'm open for that :-).

It has been a while since this package was published but I think the [instructions](https://github.com/dividab/tsconfig-paths#how-to-publish) in the readme still apply. So basically just do `yarn version` and the preversion, postversion scripts should do the publishing. 

I guess the correct semantic versioning would be a patch since it is basically a bugfix. However it may (unintentionally) break existing consumer so for that reason perhaps a major version is called for. I guess it can even be viewed as a new feature that we support other extensions which would make it a minor release. I don't really have a strong opinion on the version increment for this so you can pick what you think is appropriate.

I've added you to npm so you should be able to publish too now :-).

**Comment by jonaskello** [comment]
@cspotcode Is this ready to be merged?

**Comment by cspotcode** [comment]
Not sure, I've got my hands full with ts-node and realistically won't have
time for this in the near future.

**Comment by aleclarson** [comment]
It would be great to get this merged soon :)

**Comment by jonaskello** [comment]
Ok let's merge it then. I'm not using this package myself in any project anymore so I won't know if something stops working but I guess the community will post issues.

**Comment by jonaskello** [comment]
Ah, I did not notice there were merge conflicts. @aleclarson would you care to fix them?

**Comment by aleclarson** [comment]
Done #193 :)

**Comment by jonaskello** [comment]
Closed in #193

**Pull request closed without merging**
