### PR TITLE
Exclude not needed files from the package

### PR DESCRIPTION
**Pull request by pkuczynski**
Smaller package means faster download and install :)

### CODE REVIEW

**Comment by pkuczynski** [comment]
@jonaskello any comment?

**Comment by jonaskello** [comment]
Yes, I think this is a good idea but perhaps use `files` in package.json instead of .npmignore for the reasons in [this blog](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d).

**Comment by pkuczynski** [comment]
Actually, you already have `files` defined in `package.json` so I am not sure how those other files leaked into the package?

**Comment by pkuczynski** [comment]
Maybe because you have not published the latest version yet? Could you do that? I also modified this PR to exclude `src` using `files` field...

**Comment by jonaskello** [comment]
Aha, yes, it will be fixed at next republish then. The `src` folder actually needs to be included in order to not break things like `source-map-loader` in webpack. So I guess no change is needed, just a republish, so I'll go ahead and close this then.

**Comment by pkuczynski** [comment]
Cool, thanks for letting me know :)

**Pull request closed without merging**
